apiVersion: v1
kind: Pod
metadata:
  name: redis-emptydir
spec:
  containers:
    - name: redis
      image: redis:8.0-M04-alpine3.21
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis

  volumes:
    - name: redis-storage
      emptyDir: {}
