apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: hostpath-pod
      image: busybox:latest
      command:
        [
          "/bin/sh",
          "-c",
          "echo Hello team, this is a sample file for host volume > /output/file.txt",
        ]
      volumeMounts:
        - name: hostpath-vol
          mountPath: /output

  volumes:
    - name: hostpath-vol
      hostPath:
        path: /var/tmp
