apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistence-vol
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/tmp
