apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine3.20-perl

  nodeSelector:
    disktype: ssd

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-name
spec:
  nodeName: kube-01
  containers:
    - name: nginx
      image: nginx:stable-alpine3.20-perl

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
spec:
  containers:
    - name: app
      image: alpine:latest
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: 64Mi
          cpu: 1000m
  nodeSelector:
    disktype: ssd

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-app-2
spec:
  containers:
    - name: app
      image: alpine:latest
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: 64Mi
          cpu: 1000m
