apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-demo
spec:
  containers:
  - name: configmap-demo
    image: alpine:latest
    command: ["sleep", "3600"]

    env: # Define env variables
    - name: PLAYER_LIVES
      valueFrom: # Define the source
        configMapKeyRef: # A ConfigMap source
          name: player-pro-demo
          key: player_lives
    
    - name: PROPERTIES_FILE_NAME
      valueFrom:
        configMapKeyRef:
          name: player-pro-demo
          key: properties_file_name

    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef: # A Secret source
          name: example-secret
          key: username

    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: password