apiVersion: v1
kind: Pod
metadata:
  name: frontend-1
spec:
  containers:
  - name: app
    image: alpine:latest
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-2
spec:
  containers:
  - name: app
    image: alpine:latest
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-3
spec:
  containers:
  - name: app
    image: alpine:latest
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-4
spec:
  containers:
  - name: app
    image: alpine:latest
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"        

