apiVersion: v1
kind: Pod
metadata:
  name: restart-always-pod
spec:
  restartPolicy: Always
  containers:
  - name: restart-always-pod
    image: alpine:latest
    command:
      - sleep
      - '20'

---

apiVersion: v1
kind: Pod
metadata:
  name: on-failure-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: on-failure-pod
    image: alpine:latest
    command: ['sleep', '20']

---

apiVersion: v1
kind: Pod
metadata:
  name: never-pod
spec:
  restartPolicy: Never
  containers:
  - name: never-pod
    image: alpine:latest
    command: ['sleep', '20']

