apiVersion: v1
kind: ConfigMap
metadata:
  name: player-pro-demo
data:
  # Property like keys
  player_lives: "5"
  properties_file_name: "user-interface.properties"

  # File like keys
  base.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=10

  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true