apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
stringData:
  username: YWRtaW4K # Base 64 encoded value of "admin"
  password: cGFzc3dvcmQK # Base 64 encoded value of "password"
