apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchExpressions:
      - { key: tier, operator: In, values: [frontend] }
  template:
    metadata:
      labels:
        tier: frontend
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.20-perl
          ports:
            - containerPort: 80
