apiVersion: v1
kind: Pod
metadata:
  name: mypod-1
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: app-1
      image: gcr.io/google-samples/hello-app:1.0

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-2
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: app-2
      image: gcr.io/google-samples/hello-app:2.0
