apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine-box-replication-controller
spec:
  replicas: 3
  selector:
    app: alpine-box
  template: # Pod spec
    metadata:
      name: alpine
      labels:
        app: alpine-box
    spec:
      containers:
        - name: alpine-box
          image: alpine:latest
          command: ["sleep", "3600"]
