apiVersion: v1
kind: Pod
metadata:
  name: draining-node-test-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine3.20-perl
    ports:
    - containerPort: 80