services:
  web:
    image: vibhashanadev/python-app:latest
    deploy:
      replicas: 5
      resources:
        # Limiting each one to use, at most, 10% of a single core of CPU time and 50MB RAM.
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 4000:5000
    networks:
      - webnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
