apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP # This is the default service type
  selector: # Pod selector
    app: frontend
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
